# Generated by Django 3.2.9 on 2021-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20211129_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='person.Skill'),
        ),
    ]
