# Generated by Django 3.2.9 on 2021-11-29 19:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
