# Generated by Django 3.2.9 on 2021-11-29 21:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='resume',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
