# Generated by Django 3.2.9 on 2021-12-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.CharField(choices=[('Querétaro', 'querétaro'), ('Cdmx', 'cdmx'), ('Celaya', 'celaya')], max_length=10),
        ),
    ]
