# Generated by Django 3.2.9 on 2021-12-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_alter_person_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.CharField(choices=[('Querétaro', 'Querétaro'), ('CDMX', 'CDMX'), ('Celaya', 'Celaya')], max_length=10),
        ),
    ]
